# Generated by Django 6.1 on 2026-08-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joonsapp', '0003_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='rdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
