# Generated by Django 6.1 on 2026-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joonsapp', '0004_alter_board_rdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/')),
                ('orgfile', models.CharField(max_length=255)),
                ('filesize', models.IntegerField(default=0)),
                ('rdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
